name: MI_estimation
channels:
  - defaults
dependencies:
  - libclang==14.0.6=default_hc6dbbc7_1
  - requests==2.31.0=py39h06a4308_0
  - importlib_resources==5.2.0=pyhd3eb1b0_1
  - pycparser==2.21=pyhd3eb1b0_0
  - python-dateutil==2.8.2=pyhd3eb1b0_0
  - six==1.16.0=pyhd3eb1b0_1
  - pandas==2.0.3=py39h1128e8f_0
  - _libgcc_mutex==0.1=main
  - libgcc-ng==11.2.0=h1234567_1
  - libffi==3.4.4=h6a678d5_0
  - libwebp==1.2.4=h11a3e52_1
  - lcms2==2.12=h3be6417_0
  - numpy-base==1.25.2=py39hb5e798b_0
  - qtwebkit==5.212=h3fafdc1_5
  - kiwisolver==1.4.4=py39h6a678d5_0
  - pyqt5-sip==12.11.0=py39h6a678d5_1
  - cffi==1.15.1=py39h5eee18b_3
  - libbrotlicommon==1.0.9=h5eee18b_7
  - gstreamer==1.14.1=h5eee18b_1
  - jinja2==3.1.2=py39h06a4308_0
  - openssl==3.0.17
  - fontconfig==2.14.1=h4c34cd2_2
  - zstd==1.5.5=hc292b87_0
  - cycler==0.11.0=pyhd3eb1b0_0
  - blas==1.0=mkl
  - munkres==1.1.4=py_0
  - networkx==3.1=py39h06a4308_0
  - libbrotlidec==1.0.9=h5eee18b_7
  - fonttools==4.25.0=pyhd3eb1b0_0
  - pyopenssl==23.2.0=py39h06a4308_0
  - pytorch-cuda==11.8=h7e8668a_5
  - contourpy==1.0.5=py39hdb19cb5_0
  - libdeflate==1.17=h5eee18b_0
  - libgfortran5==11.2.0=h1234567_1
  - bzip2==1.0.8=h7b6447c_0
  - qt-main==5.15.2=h7358343_9
  - charset-normalizer==2.0.4=pyhd3eb1b0_0
  - zipp==3.11.0=py39h06a4308_0
  - python==3.9.17=h955ad1f_0
  - mysql==5.7.24=h721c034_2
  - gnutls==3.6.15=he1e5248_0
  - numpy==1.25.2=py39h5f9d8c6_0
  - torchtriton==2.0.0=py39
  - lame==3.100=h7b6447c_0
  - certifi==2025.8.3
  - krb5==1.20.1=h143b758_1
  - wheel==0.38.4=py39h06a4308_0
  - toml==0.10.2=pyhd3eb1b0_0
  - libllvm14==14.0.6=hdb19cb5_3
  - libcups==2.4.2=h2d74bed_1
  - pillow==9.4.0=py39h6a678d5_0
  - tzdata==2023c=h04d1e81_0
  - libidn2==2.3.4=h5eee18b_0
  - libcurand==10.3.3.141=0
  - cyrus-sasl==2.1.28=h52b45da_1
  - nss==3.89.1=h6a678d5_0
  - tornado==6.3.2=py39h5eee18b_0
  - jpeg==9e=h5eee18b_1
  - nettle==3.7.3=hbbd107a_1
  - dbus==1.13.18=hb2f20db_0
  - libcusolver==11.4.1.48=0
  - python-tzdata==2023.3=pyhd3eb1b0_0
  - libedit==3.1.20221030=h5eee18b_0
  - brotlipy==0.7.0=py39h27cfd23_1003
  - mpc==1.1.0=h10f8cd9_1
  - torchaudio==2.0.2=py39_cu118
  - filelock==3.9.0=py39h06a4308_0
  - pysocks==1.7.1=py39h06a4308_0
  - scipy==1.11.1=py39h5f9d8c6_0
  - libxkbcommon==1.0.1=h5eee18b_1
  - mkl_fft==1.3.6=py39h417a72b_1
  - libgomp==11.2.0=h1234567_1
  - markupsafe==2.1.1=py39h7f8727e_0
  - pytz==2022.7=py39h06a4308_0
  - numexpr==2.8.4=py39hc78ab66_1
  - mpfr==4.0.2=hb69a4c5_1
  - expat==2.5.0=h6a678d5_0
  - libxslt==1.1.37=h2085143_0
  - tk==8.6.12=h1ccaba5_0
  - mkl==2023.1.0=h213fc3f_46343
  - sqlite==3.41.2=h5eee18b_0
  - torchvision==0.15.2=py39_cu118
  - pcre==8.45=h295c915_0
  - ld_impl_linux-64==2.38=h1181459_1
  - glib==2.69.1=he621ea3_2
  - openh264==2.1.1=h4ff587b_0
  - libclang13==14.0.6=default_he11475f_1
  - tbb==2021.8.0=hdb19cb5_0
  - ncurses==6.4=h6a678d5_0
  - bottleneck==1.3.5=py39h7deecbd_0
  - libnvjpeg==11.9.0.86=0
  - brotli-bin==1.0.9=h5eee18b_7
  - _openmp_mutex==5.1=1_gnu
  - qt-webengine==5.15.9=h9ab4d14_7
  - sip==6.6.2=py39h6a678d5_0
  - cuda-cudart==11.8.89=0
  - cuda-nvrtc==11.8.89=0
  - lerc==3.0=h295c915_0
  - freetype==2.12.1=h4a9f257_0
  - brotli==1.0.9=h5eee18b_7
  - gmp==6.2.1=h295c915_3
  - libpng==1.6.39=h5eee18b_0
  - gst-plugins-base==1.14.1=h6a678d5_1
  - mpmath==1.3.0=py39h06a4308_0
  - urllib3==1.26.16=py39h06a4308_0
  - libevent==2.1.12=hdbd6064_1
  - pytorch-mutex==1.0=cuda
  - libcufft==10.9.0.58=0
  - libgfortran-ng==11.2.0=h00389a5_1
  - libuuid==1.41.5=h5eee18b_0
  - libnpp==11.8.0.86=0
  - mkl-service==2.4.0=py39h5eee18b_1
  - libxml2==2.10.4=hcbfbd50_0
  - pytorch==2.0.1=py3.9_cuda11.8_cudnn8.7.0_0
  - cuda-libraries==11.8.0=0
  - pip
  - pyqt==5.15.7=py39h6a678d5_1
  - xz==5.4.2=h5eee18b_0
  - cuda-runtime==11.8.0=0
  - nspr==4.35=h6a678d5_0
  - giflib==5.2.1=h5eee18b_3
  - idna==3.4=py39h06a4308_0
  - libcusparse==11.7.5.86=0
  - ffmpeg==4.3=hf484d3e_0
  - intel-openmp==2023.1.0=hdb19cb5_46305
  - threadpoolctl==2.2.0=pyh0d69192_0
  - cuda-cupti==11.8.87=0
  - gmpy2==2.1.2=py39heeb90bb_0
  - typing_extensions==4.7.1=py39h06a4308_0
  - libpq==12.15=hdbd6064_1
  - libunistring==0.9.10=h27cfd23_0
  - readline==8.2=h5eee18b_0
  - ply==3.11=py39h06a4308_0
  - libwebp-base==1.2.4=h5eee18b_1
  - cuda-nvtx==11.8.86=0
  - mkl_random==1.2.2=py39h417a72b_1
  - icu==58.2=he6710b0_3
  - pyparsing==3.0.9=py39h06a4308_0
  - libiconv==1.16=h7f8727e_2
  - libstdcxx-ng==11.2.0=h1234567_1
  - scikit-learn==1.3.0=py39h1128e8f_0
  - setuptools==68.0.0=py39h06a4308_0
  - libtasn1==4.19.0=h5eee18b_0
  - joblib==1.2.0=py39h06a4308_0
  - libcufile==1.7.2.10=0
  - ca-certificates==2025.11.12
  - libxcb==1.15=h7f8727e_0
  - libcublas==11.11.3.6=0
  - packaging==23.1=py39h06a4308_0
  - sympy==1.11.1=py39h06a4308_0
  - zlib==1.2.13=h5eee18b_0
  - lz4-c==1.9.4=h6a678d5_0
  - libtiff==4.5.1=h6a678d5_0
  - cryptography==41.0.3=py39hdda0065_0
  - libbrotlienc==1.0.9=h5eee18b_7
  - h5py
  - hydra-core
  - omegaconf
  - wandb
  - matplotlib[version='>=3.8']
prefix: /users/pgulat4/.conda/envs/MI_estimation
